/*
 * \brief  Dummy implementations
 * \author Automatically generated by 'gen_dummies'
 * \date   2008-11-04
 */

#include <dde_kit/printf.h>

void __alloc_bootmem(void)
{
	dde_kit_print("__alloc_bootmem called, not yet implemented!\n");
}

void add_input_randomness(void)
{
//	dde_kit_print("add_input_randomness called, not yet implemented!\n");
}

void arp_find(void)
{
	dde_kit_print("arp_find called, not yet implemented!\n");
}

char * dmi_get_system_info(void)
{
//	dde_kit_print("dmi_get_system_info called, not yet implemented!\n");
	return 0;
}

void get_option(void)
{
	dde_kit_print("get_option called, not yet implemented!\n");
}

void idle_cpu(void)
{
	dde_kit_print("idle_cpu called, not yet implemented!\n");
}

void init_srcu_struct(void)
{
	dde_kit_print("init_srcu_struct called, not yet implemented!\n");
}

void input_ff_destroy(void)
{
	dde_kit_print("input_ff_destroy called, not yet implemented!\n");
}

void input_ff_event(void)
{
	dde_kit_print("input_ff_event called, not yet implemented!\n");
}

void nr_kernel_pages(void)
{
	dde_kit_print("nr_kernel_pages called, not yet implemented!\n");
}

void on_each_cpu(void)
{
	dde_kit_print("on_each_cpu called, not yet implemented!\n");
}

void param_array_get(void)
{
	dde_kit_print("param_array_get called, not yet implemented!\n");
}

void param_array_set(void)
{
	dde_kit_print("param_array_set called, not yet implemented!\n");
}

void param_get_bool(void)
{
	dde_kit_print("param_get_bool called, not yet implemented!\n");
}

void param_set_bool(void)
{
	dde_kit_print("param_set_bool called, not yet implemented!\n");
}

void param_get_charp(void)
{
	dde_kit_print("param_get_charp called, not yet implemented!\n");
}

void param_set_charp(void)
{
	dde_kit_print("param_set_charp called, not yet implemented!\n");
}

void pci_mem_start(void)
{
	dde_kit_print("pci_mem_start called, not yet implemented!\n");
}

void pcibios_align_resource(void)
{
	dde_kit_print("pcibios_align_resource called, not yet implemented!\n");
}

void pcibios_setup(void)
{
	dde_kit_print("pcibios_setup called, not yet implemented!\n");
}

void register_cpu_notifier(void)
{
	dde_kit_print("register_cpu_notifier called, not yet implemented!\n");
}

void srcu_read_lock(void)
{
	dde_kit_print("srcu_read_lock called, not yet implemented!\n");
}

void srcu_read_unlock(void)
{
	dde_kit_print("srcu_read_unlock called, not yet implemented!\n");
}

void strnlen_user(void)
{
	dde_kit_print("strnlen_user called, not yet implemented!\n");
}

void synchronize_srcu(void)
{
	dde_kit_print("synchronize_srcu called, not yet implemented!\n");
}

void change_page_attr(void)
{
	dde_kit_print("change_page_attr called, not yet implemented!\n");
}

void global_flush_tlb(void)
{
	dde_kit_print("global_flush_tlb called, not yet implemented!\n");
}
